In [1]:
import pygame
import time
import sys
import random
from enum import Enum
import numpy as np

black = (0,0,0)
white = (255, 255, 255)
red = (255, 0, 0)
green = (0, 255, 0)
blue = (0, 0, 255)
window_size = (1000, 500)

pygame 2.0.0 (SDL 2.0.12, python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
# le ball
# window = (400, 400)
# speed = [5, 5]
# screen = pygame.display.set_mode(window)
# obj = pygame.Rect((100, 0), (10, 10))
# surface = pygame.Surface(window)
# surface.fill((255,255,255))
# pygame.draw.rect(surface, (0, 0, 0), pygame.Rect((0, 0), (10, 10)))
# while True:
 
#     obj = obj.move(speed)
#     if obj.left < 0 or obj.right > 400:
#         speed[0] = -speed[0]
#     if obj.top < 0 or obj.bottom > 400:
#         speed[1] = -speed[1]

#     screen.fill((255, 255, 255))
#     screen.blit(surface, obj)
#     pygame.display.flip()
#     time.sleep(0.1)
    
#     for event in pygame.event.get():
#         if event.type == pygame.QUIT:
#             pygame.quit()
#             break

In [3]:
# # le brownian ball
# window = (400, 400)
# screen = pygame.display.set_mode(window)
# p1 = pygame.Rect((0, 0), (10, 10))
# p2 = pygame.Rect((0, 0), (10, 10))
# objs = [p1, p2]
# s1 = pygame.Surface((10, 10))
# s2 = pygame.Surface((10, 10))
# surfs = [s1, s2]


# s1.fill(red)
# s2.fill(blue)
# # pygame.draw.rect(surface, (0, 0, 0), pygame.Rect((0, 0), (10, 10)))
# while True:
#     screen.fill((255, 255, 255))
#     step = 15
    
#     # le colision detection
    
    
#     for i in range(len(objs)):
#         x = random.randint(-step, step)
#         y = random.randint(-step, step)

#         if objs[i].left - step <= 0:
#             x = step
#         if objs[i].right + step >= 400:
#             x = -step
#         if objs[i].top - step <= 0:
#             y = step
#         if objs[i].bottom + step >= 400:
#             y = -step

#         objs[i] = objs[i].move((x, y))

#         # blit surf to screen at position of obj
#         screen.blit(surfs[i], objs[i])

#     pygame.display.flip()
#     time.sleep(0.01)
    
        
#     for event in pygame.event.get():
#         if event.type == pygame.QUIT:
#             pygame.quit()
#             break

In [4]:
def random_point(xl, xh, yl, yh):
    return random.randint(xl, xh), random.randint(yl, yh)

# step function
def step_obj(obj, step):
    x, y = random_point(-step, step, -step, step)
#     x = random.randint(-step, step)
#     y = random.randint(-step, step)

    if obj.left - step <= 0:
        x = step
    if obj.right + step >= window_size[0]:
        x = -step
    if obj.top - step <= 0:
        y = step
    if obj.bottom + step >= window_size[1]:
        y = -step
    return obj.move((x, y))

def copy(rect):
    return pygame.Rect(rect.left, rect.top, rect.width, rect.height)

In [5]:
# step = 10
# particle_size = 5

# def reproduce(particle_list, p = 0.1):
#     for i in reversed(range(len(particle_list))):
#         for j in range(i):
#             if particle_list[i].colliderect(particle_list[j]):
#                 old_pos_x, old_pos_y = particle_list[i].left, particle_list[i].top
#                 offset_x, offset_y = random_point(-step*2, step*2, -step*2, step*2)
#                 if random.randint(0, 100)/100 < p:
#                     particle_list.append(pygame.Rect((old_pos_x + offset_x, old_pos_y + offset_y), 
#                                                      (particle_size, particle_size)))
                
# def annihilate(plist1, plist2, p = 0.1):
#     delete1 = [False for _ in plist1]
#     delete2 = [False for _ in plist2]
    
#     for i in range(len(plist1)):
#         for j in range(len(plist2)):
#             if plist1[i].colliderect(plist2[j]):
#                 if random.randint(0, 100)/100 < p:
#                     delete1[i] = True
#                     delete2[j] = True
                
#     for i in reversed(range(len(plist1))):
#         if delete1[i]:
#             del plist1[i]
            
#     for j in reversed(range(len(plist2))):
#         if delete2[j]:
#             del plist2[j]       
            
# def overpop(plist, n, p=0.1):
#     # for each particle, check if there are 3 or more particles overlapping it. if yes, kill
#     neighbors = [0 for _ in plist]
#     for i in range(len(plist)):
#         for j in range(len(plist)):
#             if i != j and plist[i].colliderect(plist[j]):
#                 neighbors[i] += 1
    
#     for i in reversed(range(len(plist))):
#         if neighbors[i] >= n and random.random() < p:
#             del plist[i]
            
    
# #     for i in reversed(range(len(plist1))):
# #         collided = False
# #         for j in reversed(range(len(plist2))):
# #             if plist1[i].colliderect(plist2[i]):
# #                 collided = True
# #                 del plist2[j]
# #         if collided:
# #             del plist1[i]
                

# # le brandon
# screen = pygame.display.set_mode(window_size)


# # p1 = pygame.Rect((0, 0), (10, 10))
# # p2 = pygame.Rect((0, 0), (10, 10))
# # objs = [p1, p2]

# reds = [pygame.Rect(random_point(0, window_size[0], 0, window_size[1]), 
#                     (particle_size, particle_size)) for _ in range(100)]
# blues = [pygame.Rect(random_point(0, window_size[0], 0, window_size[1]), 
#                      (particle_size, particle_size)) for _ in range(100)]

# while True:
#     screen.fill(black)
    
#     # le colision detection
    
#     # make counter with coordinates:counts
#     # for each obj, get coords, get count
#     # if count > 2, duplicate
    
#     # loop over pairs of reds, if intersect, add a new red  to list
    
    
#     overpop(reds, 3, p=1)
#     overpop(blues, 3, p=1)
#     reproduce(reds, p=0.1)
#     reproduce(blues, p=0.1)
#     annihilate(reds, blues, p=0.1)


    
#     reds = list(map(lambda x: step_obj(x, step), reds))
#     blues = list(map(lambda x: step_obj(x, step), blues))
    
#     list(map(lambda x: pygame.draw.rect(screen, red, x), reds))
#     list(map(lambda x: pygame.draw.rect(screen, green, x), blues))
    
    
# #     for i in range(len(reds) + len(blues)):
# #         objs = reds + blues
# #         x = random.randint(-step, step)
# #         y = random.randint(-step, step)

# #         if objs[i].left - step <= 0:
# #             x = step
# #         if objs[i].right + step >= 400:
# #             x = -step
# #         if objs[i].top - step <= 0:
# #             y = step
# #         if objs[i].bottom + step >= 400:
# #             y = -step

# #         objs[i] = objs[i].move((x, y))
# #         if i > len(reds):
# #             pygame.draw.rect(screen, blue, objs[i])
# #         else:
# #             pygame.draw.rect(screen, red, objs[i])
            

#     pygame.display.update()
#     time.sleep(0.02)
    
#     # quit if population explosion
# #     if len(reds) > 1000 or len(blues) > 1000:
# #         pygame.quit()
        
#     for event in pygame.event.get():
#         if event.type == pygame.QUIT:
#             pygame.quit()
#             break

In [6]:
# step = 10
# particle_size = 5

# def reproduce(particle_list, p = 0.1):
#     for i in reversed(range(len(particle_list))):
#         for j in range(i):
#             if particle_list[i].colliderect(particle_list[j]):
#                 old_pos_x, old_pos_y = particle_list[i].left, particle_list[i].top
#                 offset_x, offset_y = random_point(-step*2, step*2, -step*2, step*2)
#                 if random.randint(0, 100)/100 < p:
#                     particle_list.append(pygame.Rect((old_pos_x + offset_x, old_pos_y + offset_y), 
#                                                      (particle_size, particle_size)))
                
# def annihilate(plist1, plist2, p = 0.1):
#     delete1 = [False for _ in plist1]
#     delete2 = [False for _ in plist2]
    
#     for i in range(len(plist1)):
#         for j in range(len(plist2)):
#             if plist1[i].colliderect(plist2[j]):
#                 if random.randint(0, 100)/100 < p:
#                     delete1[i] = True
#                     delete2[j] = True
                
#     for i in reversed(range(len(plist1))):
#         if delete1[i]:
#             del plist1[i]
            
#     for j in reversed(range(len(plist2))):
#         if delete2[j]:
#             del plist2[j]       
            
# def overpop(plist, n, p=0.1):
#     # for each particle, check if there are 3 or more particles overlapping it. if yes, kill
#     neighbors = [0 for _ in plist]
#     for i in range(len(plist)):
#         for j in range(len(plist)):
#             if i != j and plist[i].colliderect(plist[j]):
#                 neighbors[i] += 1
    
#     for i in reversed(range(len(plist))):
#         if neighbors[i] >= n and random.random() < p:
#             del plist[i]
            
    
# #     for i in reversed(range(len(plist1))):
# #         collided = False
# #         for j in reversed(range(len(plist2))):
# #             if plist1[i].colliderect(plist2[i]):
# #                 collided = True
# #                 del plist2[j]
# #         if collided:
# #             del plist1[i]
                

# # le brandon
# screen = pygame.display.set_mode(window_size)


# # p1 = pygame.Rect((0, 0), (10, 10))
# # p2 = pygame.Rect((0, 0), (10, 10))
# # objs = [p1, p2]

# reds = [pygame.Rect(random_point(0, window_size[0], 0, window_size[1]), 
#                     (particle_size, particle_size)) for _ in range(100)]
# blues = [pygame.Rect(random_point(0, window_size[0], 0, window_size[1]), 
#                      (particle_size, particle_size)) for _ in range(100)]

# while True:
#     screen.fill(black)
    
#     # le colision detection
    
#     # make counter with coordinates:counts
#     # for each obj, get coords, get count
#     # if count > 2, duplicate
    
#     # loop over pairs of reds, if intersect, add a new red  to list
    
    
#     overpop(reds, 3, p=1)
#     overpop(blues, 3, p=1)
#     reproduce(reds, p=0.1)
#     reproduce(blues, p=0.1)
#     annihilate(reds, blues, p=0.1)


    
#     reds = list(map(lambda x: step_obj(x, step), reds))
#     blues = list(map(lambda x: step_obj(x, step), blues))
    
#     list(map(lambda x: pygame.draw.rect(screen, red, x), reds))
#     list(map(lambda x: pygame.draw.rect(screen, green, x), blues))
    
    
# #     for i in range(len(reds) + len(blues)):
# #         objs = reds + blues
# #         x = random.randint(-step, step)
# #         y = random.randint(-step, step)

# #         if objs[i].left - step <= 0:
# #             x = step
# #         if objs[i].right + step >= 400:
# #             x = -step
# #         if objs[i].top - step <= 0:
# #             y = step
# #         if objs[i].bottom + step >= 400:
# #             y = -step

# #         objs[i] = objs[i].move((x, y))
# #         if i > len(reds):
# #             pygame.draw.rect(screen, blue, objs[i])
# #         else:
# #             pygame.draw.rect(screen, red, objs[i])
            

#     pygame.display.update()
#     time.sleep(0.02)
    
#     # quit if population explosion
# #     if len(reds) > 1000 or len(blues) > 1000:
# #         pygame.quit()
        
#     for event in pygame.event.get():
#         if event.type == pygame.QUIT:
#             pygame.quit()
#             break

In [7]:
# step = 10
# particle_size = 5

# def reproduce(particle_list, p = 0.1):
#     for i in reversed(range(len(particle_list))):
#         for j in range(i):
#             if particle_list[i].colliderect(particle_list[j]):
#                 old_pos_x, old_pos_y = particle_list[i].left, particle_list[i].top
#                 offset_x, offset_y = random_point(-step*2, step*2, -step*2, step*2)
#                 if random.randint(0, 100)/100 < p:
#                     particle_list.append(pygame.Rect((old_pos_x + offset_x, old_pos_y + offset_y), 
#                                                      (particle_size, particle_size)))
                
# def annihilate(plist1, plist2, p = 0.1):
#     delete1 = [False for _ in plist1]
#     delete2 = [False for _ in plist2]
    
#     for i in range(len(plist1)):
#         for j in range(len(plist2)):
#             if plist1[i].colliderect(plist2[j]):
#                 if random.randint(0, 100)/100 < p:
#                     delete1[i] = True
#                     delete2[j] = True
                
#     for i in reversed(range(len(plist1))):
#         if delete1[i]:
#             del plist1[i]
            
#     for j in reversed(range(len(plist2))):
#         if delete2[j]:
#             del plist2[j]       
            
# def overpop(plist, n, p=0.1):
#     # for each particle, check if there are 3 or more particles overlapping it. if yes, kill
#     neighbors = [0 for _ in plist]
#     for i in range(len(plist)):
#         for j in range(len(plist)):
#             if i != j and plist[i].colliderect(plist[j]):
#                 neighbors[i] += 1
    
#     for i in reversed(range(len(plist))):
#         if neighbors[i] >= n and random.random() < p:
#             del plist[i]
            
    
# #     for i in reversed(range(len(plist1))):
# #         collided = False
# #         for j in reversed(range(len(plist2))):
# #             if plist1[i].colliderect(plist2[i]):
# #                 collided = True
# #                 del plist2[j]
# #         if collided:
# #             del plist1[i]
                

# # le brandon
# screen = pygame.display.set_mode(window_size)


# # p1 = pygame.Rect((0, 0), (10, 10))
# # p2 = pygame.Rect((0, 0), (10, 10))
# # objs = [p1, p2]

# reds = [pygame.Rect(random_point(0, window_size[0], 0, window_size[1]), 
#                     (particle_size, particle_size)) for _ in range(100)]
# blues = [pygame.Rect(random_point(0, window_size[0], 0, window_size[1]), 
#                      (particle_size, particle_size)) for _ in range(100)]

# while True:
#     screen.fill(black)
    
#     # le colision detection
    
#     # make counter with coordinates:counts
#     # for each obj, get coords, get count
#     # if count > 2, duplicate
    
#     # loop over pairs of reds, if intersect, add a new red  to list
    
    
#     overpop(reds, 3, p=1)
#     overpop(blues, 3, p=1)
#     reproduce(reds, p=0.1)
#     reproduce(blues, p=0.1)
#     annihilate(reds, blues, p=0.1)


    
#     reds = list(map(lambda x: step_obj(x, step), reds))
#     blues = list(map(lambda x: step_obj(x, step), blues))
    
#     list(map(lambda x: pygame.draw.rect(screen, red, x), reds))
#     list(map(lambda x: pygame.draw.rect(screen, green, x), blues))
    
    
# #     for i in range(len(reds) + len(blues)):
# #         objs = reds + blues
# #         x = random.randint(-step, step)
# #         y = random.randint(-step, step)

# #         if objs[i].left - step <= 0:
# #             x = step
# #         if objs[i].right + step >= 400:
# #             x = -step
# #         if objs[i].top - step <= 0:
# #             y = step
# #         if objs[i].bottom + step >= 400:
# #             y = -step

# #         objs[i] = objs[i].move((x, y))
# #         if i > len(reds):
# #             pygame.draw.rect(screen, blue, objs[i])
# #         else:
# #             pygame.draw.rect(screen, red, objs[i])
            

#     pygame.display.update()
#     time.sleep(0.02)
    
#     # quit if population explosion
# #     if len(reds) > 1000 or len(blues) > 1000:
# #         pygame.quit()
        
#     for event in pygame.event.get():
#         if event.type == pygame.QUIT:
#             pygame.quit()
#             break

In [ ]:
import pygame
import time
import sys
import random
from enum import Enum
import numpy as np

black = (0,0,0)
white = (255, 255, 255)
red = (255, 0, 0)
green = (0, 255, 0)
blue = (0, 0, 255)
window_size = (1000, 500)

window_size = (500, 500)

nRed = 50
nGreen = 50

particle_size = 5
step = 15

RED = 0
GREEN = 1
BLUE = 2
    
types_to_colors = [red, green, blue]
types_to_sidelengths = [4, 6, 8]

class Particle(pygame.Rect):
    def __init__(self, top, left, typ):
        s = types_to_sidelengths[typ]
        super().__init__(top, left, s, s)
        self.typ = typ
        
    def random_nearby_particle(self, radius, typ):
        x = random.randint(self.x - radius, self.x + radius)
        y = random.randint(self.y - radius, self.y + radius)
        if x > window_size[0] - 1 or x < 0:
            x = self.x
        if y > window_size[1] - 1 or y < 0:
            y = self.y
        return Particle(x, y, typ)
        
class Simulation:
    def __init__(self, xsize, ysize, initial_particles, num_types, do_reactions):
        self.particles = initial_particles
        self.matrix = np.zeros((window_size[0], window_size[1], num_types), dtype="int16")   
        self.populate_matrix()
        self.do_reactions = do_reactions
        self.num_types = num_types
        
    def populate_matrix(self):
        for particle in self.particles:
            self.matrix[particle.x][particle.y][particle.typ] += 1
        
    # count overlapping particles, not including particle itself
    def count_overlapping(self, particle, stride = 1):
        counts = np.zeros(self.num_types, dtype="int16")
        sidelength = types_to_sidelengths[particle.typ]
        for x in range(max(0, particle.x - sidelength), min(particle.x + sidelength + 1,
                                                           window_size[0]), stride):
            for y in range(max(0, particle.y - sidelength), 
                           min(particle.y + sidelength + 1, window_size[1]), stride):
                counts += self.matrix[x][y][:]
                self.matrix[x][y][:] = 0
                
        self.matrix[particle.x][particle.y][:] = 0
        counts[particle.typ] -= 1
        assert self.matrix[particle.x][particle.y][particle.typ] == 0, \
                str((particle.x, particle.y))
        
        return counts
    
    def total_counts(self):
        counts = np.zeros(self.num_types, dtype="int64")
        for particle in self.particles:
            counts[particle.typ] += 1
        return counts
        
    def step(self):
        new_particles = []
        for particle in self.particles:
            if self.matrix[particle.x][particle.y][particle.typ] > 0:
                counts = self.count_overlapping(particle, 2)
                new_particles += do_reactions(counts, particle)
        
        self.particles = new_particles
        self.populate_matrix()
    
    def draw(self, screen):
        for particle in self.particles:
            pygame.draw.rect(screen, types_to_colors[particle.typ], particle)


reds = [Particle(random.randint(0, window_size[0] - 1), random.randint(0, window_size[1] - 1), 
                 RED) for _ in range(nRed)]
greens = [Particle(random.randint(0, window_size[0] - 1), random.randint(0, window_size[1] - 1,),
                        GREEN) for _ in range(nGreen)]
initial_particles = reds + greens

def do_reactions(counts, particle, p=0.05):
    self_count = counts[particle.typ]
    
    if self_count >= 2:
#         print("Overpop")
        return []
    if particle.typ == RED or particle.typ == GREEN:
        anti_typ = 1 - particle.typ
        if counts[anti_typ] > 0:
#             print("Annihilate")
#             return []
            return[particle.random_nearby_particle(20, BLUE)]
    if self_count >= 1:
#         print("Reproduce")
        return [particle.random_nearby_particle(20, particle.typ) for _ 
                in range(self_count + 1 + 1)]
    else:
#         print("Brownian")
        if random.random() < p and particle.typ == BLUE:
            return [particle.random_nearby_particle(step, RED), particle.random_nearby_particle(step, GREEN)]
        else:
            return [particle.random_nearby_particle(step, particle.typ)]
        
simulation = Simulation(window_size[0], window_size[1], initial_particles, 3, do_reactions)

screen = pygame.display.set_mode(window_size)
while True:
    print(simulation.total_counts())
    print("Iteration")
    screen.fill(black)
    simulation.draw(screen)
    pygame.display.update()
    simulation.step()
#     time.sleep(0.01)

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            break

[50 50  0]
Iteration
[49 49  1]
Iteration
[50 50  0]
Iteration
[50 50  0]
Iteration
[50 50  0]
Iteration
[49 49  1]
Iteration
[49 49  1]
Iteration
[49 49  1]
Iteration
[49 49  1]
Iteration
[49 49  1]
Iteration
[49 49  1]
Iteration
[49 49  1]
Iteration
[49 49  1]
Iteration
[48 48  2]
Iteration
[49 49  2]
Iteration
[50 51  1]
Iteration
[50 52  1]
Iteration
[49 53  2]
Iteration
[48 53  3]
Iteration
[47 53  4]
Iteration
[46 53  5]
Iteration
[46 53  5]
Iteration
[47 54  4]
Iteration
[48 55  4]
Iteration
[49 56  3]
Iteration
[49 57  3]
Iteration
[49 57  3]
Iteration
[49 58  3]
Iteration
[49 58  3]
Iteration
[49 57  4]
Iteration
[49 58  4]
Iteration
[49 58  5]
Iteration
[49 58  5]
Iteration
[50 59  4]
Iteration
[50 60  4]
Iteration
[50 59  5]
Iteration
[50 60  5]
Iteration
[50 60  5]
Iteration
[49 59  6]
Iteration
[49 59  6]
Iteration
[48 60  7]
Iteration
[49 62  6]
Iteration
[49 63  6]
Iteration
[49 62  6]
Iteration
[49 63  6]
Iteration
[49 63  6]
Iteration
[49 64  6]
Iteration
[49 64  6]
It

In [ ]:
assert False == True, "foobar"

In [ ]:
500*500